"""Updated db

Revision ID: d0ed2339a177
Revises: df506d531ca5
Create Date: 2024-05-08 22:36:59.651623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ed2339a177'
down_revision = 'df506d531ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Property', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=4, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
